# Generated by Django 3.2.16 on 2025-03-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250320_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_subscribed',
        ),
    ]
